server:
  port: 8020

spring:
  application:
    name: PixivPicAPI
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
http:
  maxTotal: 100
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true
  #可用空闲连接过期时间,重用空闲连接时会先检查是否空闲时间超过这个时间，如果超过，释放socket重新建立
  validateAfterInactivity: 3000000

# swagger配置
swagger:
  enabled: true
  title: '夜空-Pixiv的接口文档'
  base:
    package: com.mryunqi.pixivtgbot.controller
  description: 'Pixiv的接口文档'
  url: 'https://www.mryunqi.com'
  contact:
    name: 'Mryunqi(夜空)'
    email: '434658198@qq.com'
    url: 'https://www.mryunqi.com'
  version: v1.0.0